<?php

namespace AppBundle\Repository;

/**
 * addCaloriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class addCaloriesRepository extends \Doctrine\ORM\EntityRepository
{
}
